<a href="https://colab.research.google.com/github/Vivekkgen/Python_GenAI_training/blob/main/NumPy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# To create a NumPy array, you can use the function np.array(). np is alias of numpy library.
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#list
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
# difference between numpy array and python list by time
#list:-
%timeit [j**4 for j in range(1,9)]

2.63 µs ± 51 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#array
%timeit np.arange(1,9)**4

4.49 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Array


In [ ]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)
# y = np.array([1,2,3,4,5])

print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
l = []

for i in range(1,5):
  int_1 = int(input("enter the numbers:-"))
  l.append(int_1)
print(np.array(l))


enter the numbers:-1
enter the numbers:-2
enter the numbers:-3
enter the numbers:-4
[1 2 3 4]


# Dimensions in Array:-
> 1-D Array -->  [1,2,3,4]

> 2-D Array -->  [[1,2,3,4]]

> 3-D Array -->  [[[1,2,3,4]]]

> Higher Dimensional Array

* To find the dimensions of array we have to use "ndim" function.

In [ ]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)
# y = np.array([1,2,3,4,5])

print(y)
print(type(y))
#dimensions
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
# To create the 10 dimensions array
ar10 = np.array([1,2,3,4],ndmin = 10)
print(ar10)
print(ar10.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Spacial NumPy Array
* Array filled with 0's
* Array filled with 1's
* Create an empty array
* An arry with a range of elements
* Array diagonal element filled with 1's
* Create an array with values that are spaced linearly in a specified interval.

In [ ]:
# Array filled with 0's
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Array filled with 1's
ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


In [ ]:
#Create an empty array
ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


In [ ]:
#An arry with a range of elements
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
#Array diagonal element filled with 1's
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
# Create an array with values that are spaced linearly in a specified interval.
#linspace
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random Numbers:
```
Create NumPy Arrays with Random numbers
```
* rand() -> the function is used to generate a random value between 0 to 1.
* randn() -> the function is used to generate a random value close to zero.
This may return +ve or negatives as well.
* ranf() -> the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open intervals [0.0, 1.0).
* randint() -> the function is used to generate a random number between given range.


In [ ]:
#rand():-
var = np.random.rand(4)
print(var)

[0.61021767 0.00667378 0.43777682 0.84119571]


In [ ]:
var1 = np.random.rand(2,5)
print(var1)

[[0.05379275 0.97537655 0.63218268 0.46024114 0.4233837 ]
 [0.05352201 0.98359333 0.31035229 0.01813903 0.66775128]]


In [ ]:
#randn():-
var2 = np.random.randn(5)

print(var2)

[-0.27839212 -0.61376283 -0.5533879   0.18269372 -0.37649382]


In [ ]:
#ranf():-
var3 = np.random.ranf(4)
print(var3)

[0.07518504 0.13610638 0.52984423 0.21431761]


In [ ]:
#randint():-
#var4 = np.random.randint(min,max,total_values)
var4 = np.random.randint(5,20,5)
print(var4)

[12  5  5 18  9]


# Data Types in NumPy Arrays

In [ ]:
var = np.array([1,2,3,4,12,13,15])
print("Data Type : ",var.dtype)

Data Type :  int64


In [ ]:
var = np.array([1.0,1.2,1.3])
print("Date Type :",var.dtype)

Date Type : float64


In [ ]:
var = np.array(["A","S","D","F",1,2,3,4])
print("Date Type :",var.dtype)

Date Type : <U21


In [ ]:
# change the datatype
var = np.array([1,2,3,4,12,13,15], dtype=np.int8)
print("Data Type : ",var.dtype)
print(var)

Data Type :  int8
[ 1  2  3  4 12 13 15]


In [ ]:
var = np.array([1,2,3,4,12,13,15], dtype="f")
print("Data Type : ",var.dtype)
print(var)

Data Type :  float32
[ 1.  2.  3.  4. 12. 13. 15.]


In [ ]:
var2 = np.array([1,2,3,4,12,13,15])

new = np.float32(var2)

print("Data Type : ",var2.dtype)
print("Data Type : ",new.dtype)
print(var2)
print(new)

Data Type :  int64
Data Type :  float32
[ 1  2  3  4 12 13 15]
[ 1.  2.  3.  4. 12. 13. 15.]


In [ ]:
x2 = np.array([1,2,3,4,12,13,15])

new = np.float32(x2)

new_one = np.int_(new)

print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type :  int64
Data Type :  float32
Data Type :  int64
[ 1  2  3  4 12 13 15]
[ 1.  2.  3.  4. 12. 13. 15.]
[ 1  2  3  4 12 13 15]


In [ ]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation

In [ ]:
v = np.array([1,2,3,4])
vadd = v + 3

print(vadd)

[4 5 6 7]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [ ]:
v = np.array([1,2,3,4])
vdiv = v / 3

print(vdiv)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
v = np.array([1,2,3,4])
vdiv = v % 3

print(vdiv)

[1 2 0 1]


In [ ]:
# 2D array

In [ ]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

varadd2 = var21 + var22
print(varadd2)

[[2 4 6 8]
 [2 4 6 8]]


# Arithmetic Functions

In [3]:
var = np.array([3,2,1,4,5,3,2])
print("min : ",np.min(var),np.argmin(var))
print("max : ",np.max(var),np.argmax(var))
print("sqrt :",np.sqrt(var))
#np.argmax(var) --> return the position of that max element

min :  1 2
max :  5 4
sqrt : [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]


In [6]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))
# axis=0 --> evaluate the column elements
# axis=1 --> evaluate the row elements

[2 1 3]


In [8]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [9]:
#np.cumsum(x) --> x = [1 2 3]
#                      |\/ / +
#               o/p = [1 3 6]

# Shape & Reshaping

In [10]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)


[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [11]:
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [17]:
#Reshape
# convert the 1D into 2D array
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)
print()
x = var2.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [18]:
# convert the 1D into 3D array
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [20]:
# convert the 1D into 3D array
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

print()
# convert the 3D into 1D
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together in arithmetic operations. It makes operations between arrays of different shapes possible without explicitly reshaping or copying the data. Broadcasting follows a set of rules to determine how the arrays should be "broadcasted" or stretched to match each other's shapes.

The rules of broadcasting are as follows:

* If the arrays have a different number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

* If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

* If, after application of rule 2, the sizes still don't match, NumPy raises a "ValueError: frames are not aligned" error.

In [22]:
var1 =np.array([1,2,3,4])
var2 =np.array([1,2,3,4])
print( var1 + var2 )
# to perform addition, the dimension and number of elements are same in both array's.

[2 4 6 8]


In [25]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()
print(var1+var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [30]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
z = x+y
print(z)
print(z.shape)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
(2, 3)


# Indexing:

In [31]:
import numpy as np

var = np.array([9, 8, 7, 6])
#               0  1  2  3
#              -4 -3 -2 -1
print(var[1])
print(var[-3])

8
8


In [33]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [35]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# Slicing:
x[start:stop:step]

In [41]:
var = np.array([9, 8, 7, 6, 5, 4, 3])
#               0  1  2  3  4  5  6
print(var)

print()

print("2 to 5:",var[1:5])
print("2 to End:",var[1:])
print("start to 5:",var[:5])
print("stop :",var[1:6:2])

[9 8 7 6 5 4 3]

2 to 5: [8 7 6 5]
2 to End: [8 7 6 5 4 3]
start to 5: [9 8 7 6 5]
stop : [8 6 4]


In [54]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()

print("12 to 15 :",var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

12 to 15 : [12 13 14 15]


In [53]:
var2 = np.array([[[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]],[[11,12,13,14,15],[9,8,7,6,5],[1,2,3,4,5]]])

print(var2)
print()

print("2 to 5 :",var2[1,2,1:])

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]

 [[11 12 13 14 15]
  [ 9  8  7  6  5]
  [ 1  2  3  4  5]]]

2 to 5 : [2 3 4 5]


# Iteration in NumPy Array:

In [55]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var :
  print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [57]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
  print(j)

print()

for k in var1:
  for l in k:
    print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [58]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in var3:
  for j in i:
    for k in j:
      print(k)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [63]:
# inbuilt function : nditer()
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
  print(i)

print("stored in buffer in the form of string")
for i in np.nditer(var3, flags=['buffered'],op_dtypes=["S"]):
  print(i)


[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4
stored in buffer in the form of string
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [64]:
# inbuilt function : ndenumerate() -> iterate the element with giving their indexes.
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d)


[[[1 2 3 4]
  [1 2 3 4]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# **Copy** vs **View**:
The Difference between Copy and View:

> Copy:
* The copy owns the data.
* The copy of an array is new array.
* The changes made in the copy data does not reflect in the original array.

> View:
* The view does not own the data.
* A view of the original array.
* Any changes made to the view will affect the original array, and anychanges made to the original array will affect the view.





In [71]:
import numpy as np

var = np.array([1,2,3,4])

co = var.copy()
#var[1] = 9

print("var :",var)
print("copy :",co)

var : [1 2 3 4]
copy : [1 2 3 4]


In [70]:
x = np.array([9,8,7,6,5])

vi = x.view()
#x[1] = 9
print("x :",x)
print("view :",vi)

x : [9 8 7 6 5]
view : [9 8 7 6 5]


# Join Array:


concatenate():

In [73]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var, var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [82]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr, vr1),axis=1)

print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


stack(): It merge the arrays and works on the basis of axis


In [85]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 1)
a_new_row = np.hstack((var_1,var_2))
a_new_column = np.vstack((var_1,var_2))
a_new_height = np.dstack((var_1,var_2))
print(a_new)
print("row wise")
print(a_new_row)
print("column wise")
print(a_new_column)
print("height wise")
print(a_new_height)


[[1 9]
 [2 8]
 [3 7]
 [4 6]]
row wise
[1 2 3 4 9 8 7 6]
column wise
[[1 2 3 4]
 [9 8 7 6]]
height wise
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array:

In [88]:
var = np.array([1,2,3,4,5,6])
print(var)

ar = np.array_split(var,3)

print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [90]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var1)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print()
print(ar2)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# NumPy Arrays functions:


1. Search Array: Search an array for a certain value, and return the indexes that get a match.

In [2]:
import numpy as np
var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where( (var%2) == 0 )

print(x)

(array([0, 1, 3, 4, 6, 8]),)


In [96]:
# Search Sorted Array: which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
var1 = np.array([1,2,3,4,6,7,8])

x1 = np.searchsorted( var1 , 5)

print(x1)


4


2. Sort Array : Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [5]:
var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

var_2d = np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var_1))
print(np.sort(var_2d))

[ 1  2  3  4  5  6  7 12 22 52]
[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [4]:
var_2 = np.array(["a","s","d","f"])


print(np.sort(var_2))

['a' 'd' 'f' 's']


# Filter Array:

In [7]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]

print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


# Arithmetic Functions:

1. Shuffle:

In [8]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[1 5 4 2 3]


2. Unique:

In [12]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])

x = np.unique(var1, return_index=True,return_counts=True)

print(x)


(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


3. Resize:

In [15]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


4. flatten and ravel:
       both flatten() and ravel() functions are used to convert multi-dimensional arrays into one-dimensional arrays, but they behave differently in terms of memory usage and returned array.

   * flatten():
         * The flatten() function returns a copy of the original array collapsed into one dimension.
         * It always returns a copy of the data, even if it's already one-dimensional.
         * Changes made to the flattened array won't affect the original array.
         * The returned array is always a new one-dimensional array.

   * ravel():
         * The ravel() function returns a flattened array, but it may return a view (reference) of the original array if possible, rather than a copy.
         * If changes are made to the flattened array obtained using ravel(), they may affect the original array as well, depending on whether a copy or a view is returned.
         * The returned array may be a view of the original array, which means modifications to the returned array may modify the original array as well.

In [25]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print("2 d array :\n",y)
print()
print("converted into 1D using flatten:",y.flatten())
print("converted into 1D using ravel:",np.ravel(y))

2 d array :
 [[1 2]
 [3 4]
 [5 6]]

converted into 1D using flatten: [1 2 3 4 5 6]
converted into 1D using ravel: [1 2 3 4 5 6]


Order: {'C','F','A','K'}, Optional :     
* 'C' means to flatten in row-major (C-style) order.
* 'F' means to flatten in column-major (Fotran-style) order.
* 'A' means to flatten in column-major order if `a` is Fortran *contiguous* in memory, row-major order otherwise.
* 'K' means to flatten `a` in the order the elements occur in memory.
* The default is 'C'.

In [29]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print("2 d array :\n",y)
print()
print("converted into 1D using flatten:",y.flatten(order='C'))
print("converted into 1D using ravel:",np.ravel(y, order='A'))


2 d array :
 [[1 2]
 [3 4]
 [5 6]]

converted into 1D using flatten: [1 2 3 4 5 6]
converted into 1D using ravel: [1 2 3 4 5 6]


# NumPy Arrays Functions (**Insert** and **Delete** Function)

1 **Insert**:

In [38]:
import numpy as np

var = np.array([1,2,3,4])
print(var)

v = np.insert(var, 2 , 40)  #np.insert(array_name, position, element)
print(v)

[1 2 3 4]
[ 1  2 40  3  4]


In [35]:
var = np.array([1,2,3,4])
print(var)

v = np.insert(var, (2,4) , 40)  #np.insert(array_name, (position1,position2,...), element)
print(v)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [36]:
var = np.array([1,2,3,4])
print(var)

v = np.insert(var, (2,4) , 6.5)  #np.insert(array_name, (position1,position2,...), element)
print(v) # it did'nt insert the float value, only accept the integer part before decimal

[1 2 3 4]
[1 2 6 3 4 6]


In [45]:
var1 = np.array([[1,2,3],[1,2,3]])

print("insert based on adding new rows")
v1 = np.insert(var1, 2, 6, axis=0)
print(v1)
print()
print("insert based on adding new column")
v2 = np.insert(var1, 2, 6, axis=1)
print(v2)

insert based on adding new rows
[[1 2 3]
 [1 2 3]
 [6 6 6]]

insert based on adding new column
[[1 2 6 3]
 [1 2 6 3]]


In [49]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1, 2 , [22,23,24], axis = 0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]


2. **Append**:

In [50]:
var = np.array([1,2,3,4])
print(var)

x = np.append(var, 6.5)
print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [51]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.append(var1,[[45,44,23]],axis=0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


3. **Delete**:

In [53]:
import numpy as np

var1 = np.array([1,2,3,4])
print(var1)
print(f"{var1[2]} are deleted")
d = np.delete(var1, 2)
print(d)

[1 2 3 4]
3 are deleted
[1 2 4]


# **Matrix** in NumPy Arrays:

Create a matrix in numpy array's:

In [8]:
import numpy as np

var =  np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var+var2)
print(var-var2)
print(var*var2)
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[2 4]
 [2 4]]
[[0 0]
 [0 0]]
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [9]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [12]:
var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [13]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


Inverse of matrix: A^-1

In [14]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


Power of matrix: np.linalg.matrix_power(var, n)
                  
                  n -> n<0 , n=0 , n>0
                  n=0  I  [1 0]
                          [0 1]
                  n>0  power(mult)
                  n<0  Inverse X power

In [17]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))  #case2
print()

print(np.linalg.matrix_power(var4,0))  #case1
print()

print(np.linalg.matrix_power(var4,-2)) #case3
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



Determinate: np.linalg.det(var)

In [19]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5)) #0.0 because two row's are same or identical

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
